### ISSUE TITLE
Update is not running on Jenkins any more

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/chimeratk.github.io#1]
To build the documentation, cmake has to run through and each project needs all of its dependencies. This is not working for the "systemlike" installation any more.
The project needs to be moved to the new pipeline scheme and the job needs all the necessary dependencies.

The job should become red if any project is failing. Currently it is set to yellow because the job would terminate and not build the following docus if one project fails. This should be fixed in the job when it is changed.

**Comment by mhier** [comment]
I changed the update script so it no longer needs to run cmake. It will now manually create the Doxyfile from the template (based on information extracted from CMakeLists.txt). For sphinx-based documentation, it will create the conf.py file in a similar way.
